org.gradle.jvmargs=-Xmx4G -Dhttps.protocols=TLSv1.2,TLSv1.3 -Djavax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000

# 代理配置 (HTTP/HTTPS) — 如需要请取消注释
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7897
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7897
# systemProp.http.nonProxyHosts=localhost|127.0.0.1

# Minecraft & NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.243
neo_version_range=[21.1.243,21.2.0)
loader_version_range=[4,5)

# Mod Properties
mod_id=ae2_pattern_disk
mod_name=AE2 Pattern Disk
mod_license=LGPL-3.0
mod_version=0.1.1
mod_group_id=io.github.lounode.ae2pattern
mod_authors=星落
mod_description=AE2 addon that adds pattern disks to store many encoded patterns by type, plus a transferer and pattern disk provider.

# Mod dependencies
ae2_version=19.2.8
guideme_version=21.1.15
org.gradle.java.home=C:/Java/jdk-21
